### ISSUE TITLE
Introduce Linter

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#110]
The codebase is in a mixed state, and sadly, not even gofmt is applied everywheren.
We want to change this.

### Roadmap

1. [ ] `gomft` / `goimports` project (`goimports` is a superset of `gofmt`)
1. [ ] Make https://github.com/mgechev/revive happy (config that might be a good start, tested on master https://gist.github.com/problame/ff35670c481ed9b74f9680b60f67c727)
1. [ ] Evaluate https://github.com/alecthomas/gometalinter
1. [ ] Integrate linters into Makefile & CI
    * Must use frozen version of linters
     * CI should fail but run all jobs if linting fails (WIP PRs from people without proper test infra)

**Comment by problame** [comment]
Maybe consider https://github.com/golangci/golangci-lint

**Comment by problame** [comment]
This was done in #159
